/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/office.glb 
Author: SeverDoes3D (https://sketchfab.com/SeverDoes3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-assets-16c1a779bb0a4055a26367741d39e059
Title: Office - Assets
*/

import React from 'react'
import { useEffect, useRef } from 'react'
import { useGLTF, Html, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export default function Office( ...props) {
  const { nodes, materials } = useGLTF('/assets/models/office.glb')
  const hackathonPhotoTexture = useTexture('/assets/images/hackathon.JPG')
  const familyPhotoTexture = useTexture('/assets/images/family.JPG')
  const volleyballPhotoTexture = useTexture('/assets/images/volleyball_sh.JPG')
  const graduationPhototexture = useTexture('/assets/images/graduation.JPG')
  const diplomaPhotoTexture = useTexture('/assets/images/diploma.jpg')
  const posterTexture = useTexture('/assets/images/poster.png')
  
  const groupRef = useRef()

    const CAMERA_PRESETS = {
      computer: {
        direction: new THREE.Vector3(1, 0.1, 0.3).normalize(),
        radius: 0.6   // 🔥 direct control
      },
      frame: {
        direction: new THREE.Vector3(1, 0.1, 0.1),
        radius: 0.4
      },
      deskframe: {
        direction: new THREE.Vector3(1, 0.1, -0.3),
        radius: 0.4
      },
      pinboard: {
        direction: new THREE.Vector3(1, 0.1, -0.1),
        radius: 0.6
      },
      diploma: {
        direction: new THREE.Vector3(1, -0.8, 0),
        radius: 0.62
      },
      poster: {
        direction: new THREE.Vector3(1, -1, 0),
        radius: 0.7
      }
    }

    useEffect(() => {
      if (!groupRef.current) return

      const box = new THREE.Box3().setFromObject(groupRef.current)
      const center = box.getCenter(new THREE.Vector3())
      const size = box.getSize(new THREE.Vector3())

      // ✅ center model
      groupRef.current.position.sub(center)

      // ✅ optional: normalize scale (VERY useful)
      const maxDim = Math.max(size.x, size.y, size.z)
      const scale = 3 / maxDim   // adjust "3" for desired size
      groupRef.current.scale.setScalar(scale)

    }, [])

    const focus = (preset, object) => {
      object.updateWorldMatrix(true, true)

      const box = new THREE.Box3().setFromObject(object)
      const center = box.getCenter(new THREE.Vector3())
      const size = box.getSize(new THREE.Vector3())

      const maxDim = Math.max(size.x, size.y, size.z)
      const radius = preset.radius ?? maxDim * preset.radiusMultiplier

      // 🔥 get object's WORLD rotation
      const worldQuaternion = object.getWorldQuaternion(new THREE.Quaternion())

      // 🔥 apply rotation to direction
      const direction = preset.direction.clone().normalize()

      // 🔥 final camera position
      const cameraPos = center.clone().add(direction.multiplyScalar(radius))

      const spherical = new THREE.Spherical().setFromVector3(direction)
      spherical.radius = radius

      //const offset = cameraPos.clone().sub(center)
      //const spherical = new THREE.Spherical().setFromVector3(offset)

      console.log('dispatching radius:', preset.radius)

      window.dispatchEvent(
        new CustomEvent('focusObject', {
          detail: {
            target: [center.x, center.y, center.z],
            radius: radius,
            theta: spherical.theta,
            phi: spherical.phi
          }
        })
      )
      
      /*
      window.dispatchEvent( 
        new CustomEvent('focusObject', { 
          detail: { 
            target: [center.x, center.y, center.z], 
            position: [cameraPos.x, cameraPos.y, cameraPos.z] // 🔥 NEW 
          } 
        }) 
      )
      */
}
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group position={[-0.051, 0.743, 0.876]} rotation={[0, -0.736, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.M_Cactus_1024} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.M_Cactus_1024} position={[0.01, 0.122, 0.014]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.M_Cactus_1024} position={[0.001, 0.123, -0.001]} />
      </group>
      <group position={[-0.235, 1.321, 2.261]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.381} onClick={(e) => {e.stopPropagation(); focus(CAMERA_PRESETS.pinboard, e.object)}}>
        <mesh geometry={nodes.Object_30.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} >
          <mesh position={[0, 0.08, 0]} rotation={[-Math.PI/2, 0, 0]}>
          <planeGeometry args={[1.76, 1.23]} />
          <meshStandardMaterial map={diplomaPhotoTexture} />
        </mesh>
        </mesh>
        <mesh geometry={nodes.Object_32.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.433, 0.031, -0.442]} rotation={[-0.02, -0.022, 0]} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.441, 0.037, 0.073]} rotation={[-0.032, 0.035, 0]} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.117, 0.031, -0.374]} rotation={[-0.047, -0.054, 0.003]} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.443, 0.03, 0.199]} rotation={[-0.068, 0.063, 0.004]} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.583, 0.03, -0.495]} rotation={[-0.034, -0.059, -0.003]} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.192, 0.038, -0.433]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.591, 0.04, -0.475]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.683, 0.043, -0.418]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.437, 0.044, 0.092]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.483, 0.038, 0.226]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.116, 0.037, -0.358]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={2.627} />
      </group>
      <group position={[0.035, 0.743, 1.904]} rotation={[-Math.PI, 1.358, -Math.PI]}>
        <mesh geometry={nodes.Object_70.geometry} material={materials.M_TapeRecorder_1024} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.M_TapeRecorder_Tape_Rotors_Glass_1024} />
      </group>
      <group position={[-0.22, 2.009, 2.101]}>
        <group position={[0.048, -0.008, 0]}>
          <mesh geometry={nodes.Object_77.geometry} material={materials.M_Vent_1024} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.M_Vent_1024} rotation={[Math.PI / 3, 0, 0]} />
        </group>
        <group position={[0.133, 0.004, 0]}>
          <group position={[-0.159, -0.004, 0]}>
            <mesh geometry={nodes.Object_89.geometry} material={materials.M_Vent_1024} />
            <mesh geometry={nodes.Object_91.geometry} material={materials.M_Vent_1024} position={[0.01, 0.006, 0]} />
            <mesh geometry={nodes.Object_93.geometry} material={materials.M_Vent_1024} position={[0.13, -0.019, 0.186]} />
          </group>
          <mesh geometry={nodes.Object_85.geometry} material={materials.M_Vent_1024} />
          <mesh geometry={nodes.Object_87.geometry} material={materials.M_Vent_1024} position={[0, -0.114, 0]} />
        </group>
        <mesh geometry={nodes.Object_75.geometry} material={materials.M_Vent_1024} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.M_Vent_1024} position={[-0.004, 0.157, 0.238]} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.M_Vent_1024} position={[-0.01, 0, 0]} />
      </group>
      <group position={[0.996, 0.565, 0.619]} rotation={[-3.126, -1.002, -1.576]}>
        <mesh geometry={nodes.Object_101.geometry} material={materials.M_Clipboard_Notepad_1024} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.M_Clipboard_Notepad_1024} position={[0.006, -0.034, 0.001]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.381} />
      </group>
      <group position={[-0.039, 0.743, 1.563]} rotation={[0, 0.454, 0]}>
        <group position={[0, 0.061, 0]} rotation={[0, 0, 0.811]}>
          <group position={[0, 0.118, 0]} rotation={[0, 0, -0.976]}>
            <group position={[0, 0.279, 0]} rotation={[0, 0, -0.491]}>
              <group position={[0, 0.366, 0]} rotation={[0, 0, -0.603]}>
                <mesh geometry={nodes.Object_117.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
                <mesh geometry={nodes.Object_119.geometry} material={materials['M_Lamps_CCTV_2048.001']} position={[0, 0.083, 0]} />
              </group>
              <mesh geometry={nodes.Object_115.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
            </group>
            <mesh geometry={nodes.Object_113.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
          </group>
          <mesh geometry={nodes.Object_111.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
        </group>
        <mesh geometry={nodes.Object_109.geometry} material={materials['M_Lamps_CCTV_2048.001']} />
      </group>
      <group
        onClick={(e) => {
          e.stopPropagation()
          focus(CAMERA_PRESETS.computer, e.object)
        }}
      >
        <mesh geometry={nodes.Object_10.geometry} material={materials.M_Computer_2048} position={[0.488, 0.743, 0.925]} rotation={[0, 0.168, 0]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.M_Computer_2048} position={[0.533, 0.743, 0.53]} rotation={[0, -0.169, 0]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.M_Computer_2048} position={[0.061, 0.743, 0.472]} rotation={[0, -0.387, 0]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.M_Computer_2048} position={[0.103, 0.91, 0.502]} rotation={[0, -0.269, 0]} >
          
        <group rotation={[0, Math.PI, 0]}>
            <Html
              transform
              occlude={false}
              distanceFactor={0.13}
              position={[-0.12, 0.265, 0]}   // small offset outward
              rotation={[0, -Math.PI/2, 0]}
              style={{
                pointerEvents: 'auto',
                willChange: 'transform'
              }}
            >
              <iframe
                src="https://tengis-portfolio.netlify.app"
                style={{
                  width: '1200px',
                  height: '880px',
                  border: 'none',
                  borderRadius: '6px',
                  background: 'black',
                }}
              />
            </Html>
          </group>
        </mesh>
        
      </group>
    
      <mesh geometry={nodes.Object_18.geometry} material={materials.M_Filebox_1024} position={[-0.084, 0.743, 1.283]} rotation={[0, 1.531, 0]} scale={[1.096, 1, 1]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_20.geometry} material={materials.M_Filebox_1024} position={[-0.075, 0.743, 1.398]} rotation={[-Math.PI, 1.512, -Math.PI]} scale={[1.096, 1, 1]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_22.geometry} material={materials.M_Filebox_1024} position={[-0.084, 0.743, 1.281]} rotation={[0, 1.531, 0]} scale={[1.096, 1, 1]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_24.geometry} material={materials.M_Filebox_1024} position={[-0.075, 0.743, 1.398]} rotation={[-Math.PI, 1.512, -Math.PI]} scale={[1.096, 1, 1]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_26.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[0.363, 0.743, 1.741]} rotation={[-0.005, 1.388, 0.005]} scale={[0.381, 0.137, 0.381]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_28.geometry} material={materials.M_Office_PinBoard_Photo_Notepad_1024} position={[-0.034, 0.743, 1.116]} rotation={[Math.PI / 2, 0, -1.814]} scale={0.381} onClick={(e) => {e.stopPropagation(); focus(CAMERA_PRESETS.deskframe, e.object)}}> 
        <mesh position={[0, 0.01, -0.28]} rotation={[Math.PI /2 - 0.18, Math.PI, Math.PI]}>
          <planeGeometry args={[0.3, 0.44]} />
          <meshStandardMaterial map={familyPhotoTexture} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.Object_54.geometry} material={materials.M_Sigarettes_512} position={[0.481, 0.747, 1.504]} rotation={[1.002, 0.422, 0.998]} scale={0.5} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_56.geometry} material={materials.M_Sigarettes_512} position={[0.382, 0.752, 1.511]} rotation={[Math.PI, -1.189, -1.886]} scale={0.5} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_58.geometry} material={materials.M_Sigarettes_512} position={[0.487, 0.743, 1.35]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_60.geometry} material={materials.M_Sigarettes_512} position={[0.446, 0.764, 1.309]} rotation={[-1.448, -0.189, -2.328]} scale={0.5} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_62.geometry} material={materials.M_Sigarettes_512} position={[0.53, 0.766, 1.406]} rotation={[-1.697, -0.143, 0.343]} scale={0.5} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_64.geometry} material={materials.M_Sigarettes_512} position={[0.487, 0.752, 1.35]} scale={[1, 0.45, 1]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_66.geometry} material={materials.M_Sigarettes_512} position={[0.451, 0.752, 1.464]} rotation={[0, -0.571, 1.574]} scale={0.5} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_68.geometry} material={materials.M_Table_2048} position={[0.213, 0.006, 1.171]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_73.geometry} material={materials.M_TapeRecorder_Tape_Rotors_Glass_1024} position={[0.445, 0.743, 1.958]} rotation={[0, 0.361, 0]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_95.geometry} material={materials.Poster_1024} position={[-0.246, 1.568, 1.317]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.619, 0.309, 0.619]} onClick={(e) => {e.stopPropagation(); focus(CAMERA_PRESETS.poster, e.object)}} >
        <mesh position={[0, 0.08, 0]} rotation={[Math.PI/2, Math.PI, Math.PI]}>
          <planeGeometry args={[1.25, 1]} />
          <meshStandardMaterial map={posterTexture} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.Object_97.geometry} material={materials.PhotoFrame_20x30_likeA4_512} position={[-0.241, 1.27, -0.097]} rotation={[0, -Math.PI / 2, 0]} scale={[0.992, 0.992, 1.118]} onClick={(e) => {e.stopPropagation(); focus(CAMERA_PRESETS.frame, e.object)}}> 
        <mesh position={[0, 0, -0.02]} rotation={[0, Math.PI, 0]}>
          <planeGeometry args={[0.33, 0.23]} />
          <meshStandardMaterial map={hackathonPhotoTexture} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.Object_99.geometry} material={materials.PhotoFrame_20x30_likeA4_512} position={[-0.241, 1.628, 0.369]} rotation={[0, -Math.PI / 2, 0]} scale={[0.992, 0.992, 1.118]} onClick={(e) => {e.stopPropagation(); focus(CAMERA_PRESETS.frame, e.object)}}>
        <mesh position={[0, 0, -0.02]} rotation={[0, Math.PI, 0]}>
          <planeGeometry args={[0.33, 0.23]} />
          <meshStandardMaterial map={volleyballPhotoTexture} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.Object_105.geometry} material={materials.M_Clipboard_Notepad_1024} position={[0.235, 0.743, 1.171]} rotation={[0, 0.319, Math.PI / 2]} onClick={(e) => {console.log(e.object)}}/>
      <mesh geometry={nodes.Object_107.geometry} material={materials.M_OfficeStool_Bin_2048} position={[0.923, 0.008, 0.77]} rotation={[-Math.PI, -0.416, -Math.PI]} scale={[1.235, 1, 1.235]} onClick={(e) => {console.log(e.object)}}/>
    </group>
  )
}

useGLTF.preload('/assets/models/office.glb')
